-- app_db — the full migration lineage 0001–0002 as ONE file.
--
-- GENERATED by backend/scripts/build-single-migration.mjs. Do not edit;
-- regenerate after any new migration. Each numbered section below is the
-- corresponding backend/migrations file, VERBATIM and in order — this
-- bundle and `node scripts/migrate.mjs up` produce identical databases.
--
-- Run once, on an EMPTY database you create first:
--   psql -v ON_ERROR_STOP=1 -d app_db -f app_single_migration.sql
--
-- Everything runs in one transaction: any error rolls back the lot.
-- The final section records the lineage in public.app_migrations, so the
-- Node runner recognises this database and future numbered migrations
-- apply on top normally.

SET client_encoding = 'UTF8';
BEGIN;

-- ============================================================================
-- 0001_baseline.sql
-- ============================================================================

-- 0001 — baseline: the app schema and the infrastructure tables every
-- deployment needs before any feature exists.
--
-- Conventions this lineage follows (see docs/ARCHITECTURE.md):
--   * Migrations are the ONLY schema channel. Add new numbered files; never
--     edit one that has been applied anywhere.
--   * Business logic lives in app.api_* SQL functions returning JSONB shaped
--     as the contract's camelCase — routes stay thin (src/db/pool.ts callApi).
--   * Every migration has a paired .down.sql.

CREATE SCHEMA IF NOT EXISTS app;

SET search_path = app, public;

-- ============================================================================
-- 1. CONFIG (config-not-code: operational dials live in rows, not images)
-- ============================================================================
CREATE TABLE app.config (
    key        TEXT PRIMARY KEY,
    value      JSONB NOT NULL,
    updated_by TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The console's change log. APPEND-ONLY, ENFORCED HERE rather than promised
-- by callers: an audit trail whose rows can be edited is a diary, not a
-- record. from/to are audit-readable phrases, not machine state.
CREATE TABLE app.config_audit (
    audit_id   BIGSERIAL PRIMARY KEY,
    setting    TEXT NOT NULL,
    from_value TEXT,
    to_value   TEXT,
    changed_by TEXT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION app.config_audit_immutable()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'app.config_audit is append-only';
END;
$$;

CREATE TRIGGER trg_config_audit_immutable
    BEFORE UPDATE OR DELETE ON app.config_audit
    FOR EACH ROW EXECUTE FUNCTION app.config_audit_immutable();

-- ============================================================================
-- 2. IDEMPOTENCY (durable fallback when Redis is off — middleware/idempotency)
-- ============================================================================
CREATE TABLE app.action_idempotency (
    action_uuid TEXT PRIMARY KEY,
    subject     TEXT,
    actor       TEXT NOT NULL,
    action      TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- 3. MFA / WebAuthn store (src/mfa/store.ts)
--
-- Three tables instead of three in-memory Maps, so any instance answers
-- correctly and a redeploy does not erase enrolled passkeys. TTL semantics
-- live in the rows (expires_at); single-use guarantees are
-- DELETE ... RETURNING atomicity. Credential ids and challenges are base64url
-- strings exactly as @simplewebauthn speaks them; the COSE key is raw bytes.
-- ============================================================================
CREATE TABLE app.mfa_credentials (
    credential_id TEXT PRIMARY KEY,
    username      TEXT NOT NULL,
    public_key    BYTEA NOT NULL,
    counter       BIGINT NOT NULL DEFAULT 0,
    device_type   TEXT,
    backed_up     BOOLEAN,
    transports    TEXT[],
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_mfa_credentials_username ON app.mfa_credentials (username);

-- One-time login tokens (the desktop's pending sign-in approvals). Three-
-- minute lifetime, enforced in every read (expires_at > now()); expired rows
-- are swept opportunistically on each token mint.
CREATE TABLE app.mfa_login_tokens (
    token      TEXT PRIMARY KEY,
    username   TEXT NOT NULL,
    status     TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'verified')),
    challenge  TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_mfa_login_tokens_expires ON app.mfa_login_tokens (expires_at);

-- Enrolment ceremony challenges, one in flight per username.
CREATE TABLE app.mfa_registration_challenges (
    username   TEXT PRIMARY KEY,
    challenge  TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL
);

-- ============================================================================
-- 4. PASSWORD INVITATIONS (src/services/passwordInvitations.ts)
--
-- Accounts are provisioned with no password; a single-use link, mailed to the
-- address on the account, is the only way to set one. THE TOKEN NEVER LANDS
-- HERE — only its SHA-256, so a database copy cannot be turned into working
-- links. Single use is the primary key's job: the claim is one atomic UPDATE
-- (used_at IS NULL AND expires_at > now() ... RETURNING), so two browsers
-- racing cannot both win. No FK to a user — the user lives in Keycloak;
-- kc_user_id is the realm's uuid and this database cannot police it.
-- ============================================================================
CREATE TABLE app.password_invitations (
    token_hash  TEXT PRIMARY KEY,
    kc_user_id  TEXT NOT NULL,
    username    TEXT NOT NULL,
    email       TEXT NOT NULL,
    -- 'provision' = a new account that has never had a password.
    -- 'reset'     = an existing account whose holder has lost theirs.
    -- The distinction is the EMAIL's wording, not the mechanism.
    purpose     TEXT NOT NULL DEFAULT 'provision'
                CHECK (purpose IN ('provision', 'reset')),
    created_by  TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ NOT NULL,
    used_at     TIMESTAMPTZ,
    -- Whether the relay ACCEPTED the message. False with a row present is a
    -- real and useful state: the invitation exists and can be resent without
    -- minting a second one.
    mailed      BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_password_invitations_user
    ON app.password_invitations (kc_user_id, created_at DESC);
CREATE INDEX idx_password_invitations_expires
    ON app.password_invitations (expires_at);

-- One row per account — the most recent invitation, whatever became of it —
-- with the usable-state verdict derived HERE so the browser cannot disagree
-- with the server about whether a link still works.
CREATE OR REPLACE FUNCTION app.api_password_invitations()
RETURNS JSONB LANGUAGE sql AS $$
    SELECT COALESCE(jsonb_agg(row), '[]'::jsonb)
    FROM (
        SELECT DISTINCT ON (kc_user_id) jsonb_build_object(
            'kcUserId',  kc_user_id,
            'username',  username,
            'email',     email,
            'purpose',   purpose,
            'createdBy', created_by,
            'createdAt', created_at,
            'expiresAt', expires_at,
            'usedAt',    used_at,
            'mailed',    mailed,
            'state',     CASE
                             WHEN used_at IS NOT NULL      THEN 'set'
                             WHEN expires_at <= now()      THEN 'expired'
                             WHEN NOT mailed               THEN 'not_sent'
                             ELSE                               'invited'
                         END
        ) AS row
        FROM app.password_invitations
        ORDER BY kc_user_id, created_at DESC
    ) latest;
$$;

COMMENT ON TABLE app.password_invitations IS
    'Single-use set-password links. Stores the token hash only; the token exists in the email.';

-- ============================================================================
-- 0002_notes.sql
-- ============================================================================

-- 0002 — the NOTES example: one entity wired through every convention.
--
-- THIS IS THE TEACHING MIGRATION. Delete it (apply 0002_notes.down.sql, or
-- start your fork from 0001) or rename everything to your first real entity.
-- The pattern it demonstrates:
--
--   * The table owns its data; the api_* functions own the CONTRACT — they
--     return JSONB shaped as the API's camelCase, so routes stay thin
--     (src/services/notes.ts is a callApi() wrapper per operation).
--   * Business rules live HERE (RAISE EXCEPTION -> 422 via the error
--     handler's P0001 mapping), not in Express.
--   * Writes stamp who and when; the route passes the verified principal's
--     username as p_actor.

SET search_path = app, public;

CREATE TABLE app.notes (
    note_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title      TEXT NOT NULL CHECK (length(trim(title)) > 0),
    body       TEXT NOT NULL DEFAULT '',
    tags       TEXT[] NOT NULL DEFAULT '{}',
    created_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by TEXT,
    updated_at TIMESTAMPTZ
);

CREATE INDEX idx_notes_created ON app.notes (created_at DESC);

-- One row -> the contract's camelCase shape, defined once and reused by
-- every function below so list and detail can never disagree.
CREATE OR REPLACE FUNCTION app.note_json(n app.notes)
RETURNS JSONB LANGUAGE sql IMMUTABLE AS $$
    SELECT jsonb_build_object(
        'noteId',    n.note_id,
        'title',     n.title,
        'body',      n.body,
        'tags',      to_jsonb(n.tags),
        'createdBy', n.created_by,
        'createdAt', n.created_at,
        'updatedBy', n.updated_by,
        'updatedAt', n.updated_at
    );
$$;

-- List with optional search + paging. Returns {items, total} so the client
-- can page without a second count query.
CREATE OR REPLACE FUNCTION app.api_notes_list(p_q TEXT, p_limit INT, p_offset INT)
RETURNS JSONB LANGUAGE sql STABLE AS $$
    WITH filtered AS (
        SELECT n.* FROM app.notes n
        WHERE p_q IS NULL OR p_q = ''
           OR n.title ILIKE '%' || p_q || '%'
           OR n.body  ILIKE '%' || p_q || '%'
        ORDER BY n.created_at DESC
    ),
    page AS (
        SELECT * FROM filtered
        LIMIT  COALESCE(NULLIF(p_limit, 0), 50)
        OFFSET COALESCE(p_offset, 0)
    )
    SELECT jsonb_build_object(
        'items', COALESCE((SELECT jsonb_agg(app.note_json(page.*)) FROM page), '[]'::jsonb),
        'total', (SELECT count(*) FROM filtered)
    );
$$;

CREATE OR REPLACE FUNCTION app.api_notes_get(p_note_id UUID)
RETURNS JSONB LANGUAGE sql STABLE AS $$
    SELECT app.note_json(n.*) FROM app.notes n WHERE n.note_id = p_note_id;
$$;

CREATE OR REPLACE FUNCTION app.api_notes_create(p JSONB)
RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
    created app.notes;
BEGIN
    IF length(trim(COALESCE(p->>'title', ''))) = 0 THEN
        RAISE EXCEPTION 'A note needs a title.';
    END IF;
    INSERT INTO app.notes (title, body, tags, created_by)
    VALUES (
        trim(p->>'title'),
        COALESCE(p->>'body', ''),
        COALESCE((SELECT array_agg(t) FROM jsonb_array_elements_text(p->'tags') AS t), '{}'),
        COALESCE(p->>'actor', 'unknown')
    )
    RETURNING * INTO created;
    RETURN app.note_json(created);
END;
$$;

CREATE OR REPLACE FUNCTION app.api_notes_update(p_note_id UUID, p JSONB)
RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
    updated app.notes;
BEGIN
    UPDATE app.notes SET
        title      = CASE WHEN p ? 'title' THEN trim(p->>'title') ELSE title END,
        body       = CASE WHEN p ? 'body'  THEN p->>'body'        ELSE body  END,
        tags       = CASE WHEN p ? 'tags'
                          THEN COALESCE((SELECT array_agg(t)
                                           FROM jsonb_array_elements_text(p->'tags') AS t), '{}')
                          ELSE tags END,
        updated_by = COALESCE(p->>'actor', 'unknown'),
        updated_at = now()
    WHERE note_id = p_note_id
    RETURNING * INTO updated;
    IF NOT FOUND THEN
        RETURN NULL;  -- the route answers 404
    END IF;
    IF length(trim(updated.title)) = 0 THEN
        RAISE EXCEPTION 'A note needs a title.';
    END IF;
    RETURN app.note_json(updated);
END;
$$;

CREATE OR REPLACE FUNCTION app.api_notes_delete(p_note_id UUID)
RETURNS JSONB LANGUAGE plpgsql AS $$
DECLARE
    n INT;
BEGIN
    DELETE FROM app.notes WHERE note_id = p_note_id;
    GET DIAGNOSTICS n = ROW_COUNT;
    RETURN jsonb_build_object('deleted', n > 0);
END;
$$;

-- ============================================================================
-- migration bookkeeping — mark the whole lineage applied
-- ============================================================================

-- Some target databases have no public schema; the runner recreates it the
-- same way — see scripts/migrate.mjs.
CREATE SCHEMA IF NOT EXISTS public;
CREATE TABLE IF NOT EXISTS public.app_migrations (
    name       TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO public.app_migrations (name) VALUES
    ('0001_baseline.sql'),
    ('0002_notes.sql');

COMMIT;
