import { defineConfig, loadEnv, type Plugin, type ViteDevServer } from 'vite'
import { fileURLToPath, URL } from 'node:url'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

/**
 * Serve `/config.js` from plain-named environment variables, exactly as the
 * container's docker/40-runtime-config.sh does.
 *
 * WITHOUT THIS, THE SAME .env FILE MEANS TWO DIFFERENT THINGS. runtime.ts
 * reads `window.__ENV__.KC_URL` and falls back to `import.meta.env.VITE_KC_URL`.
 * In a container the entrypoint writes /config.js and populates window.__ENV__,
 * so `KC_URL=...` works; under `npm run dev` nothing populated it, so the same
 * line did nothing and only `VITE_KC_URL=...` had any effect. One deployment
 * file could not drive both — and the obvious fix, prefixing everything with
 * VITE_, is the dangerous one, because it inlines server-side secrets into the
 * bundle.
 *
 * Only the browser-safe keys are published, the same list the entrypoint
 * writes. Upstreams and credentials are deliberately absent: they are the
 * proxy's business, and anything in this object is readable by anyone.
 */
function runtimeConfigPlugin(env: Record<string, string>): Plugin {
  const body = () =>
    `// Generated by vite.config.ts for the dev server, mirroring docker/40-runtime-config.sh.\n` +
    `window.__ENV__ = ${JSON.stringify(
      {
        KC_URL: env.KC_URL ?? '',
        KC_REALM: env.KC_REALM ?? '',
        API_BASE: env.API_BASE ?? '',
        USERS_BASE: env.USERS_BASE ?? '',
        MFA_ENABLED: env.MFA_ENABLED ?? '',
        MFA_BASE: env.MFA_BASE ?? '',
        APP_NAME: env.APP_NAME ?? '',
      },
      null,
      2,
    )}\n`

  return {
    name: 'app-runtime-config',
    configureServer(server: ViteDevServer) {
      // Registered in the body of configureServer, not in a returned function,
      // so it runs BEFORE Vite's static handler and wins over the placeholder
      // in public/config.js.
      server.middlewares.use((req, res, next) => {
        if (req.url?.split('?')[0] !== '/config.js') return next()
        res.setHeader('Content-Type', 'application/javascript')
        res.setHeader('Cache-Control', 'no-store')
        res.end(body())
      })
    },
  }
}

export default defineConfig(({ mode }) => {
  // '' rather than 'VITE_' so server-side-only values are visible here. They
  // are never returned to the client — only used to build the proxies below.
  const env = loadEnv(mode, process.cwd(), '')
  // The backend. Server-side only — the browser is told '/app/v1' and nothing
  // more (RUNTIME_CONFIG.apiBase), so the backend's address never enters the
  // bundle and moving it is a dev-server restart rather than a rebuild.
  const apiUpstream = (env.API_UPSTREAM || 'http://localhost:8081').replace(/\/+$/, '')
  // Keycloak, for the admin-API proxy below.
  const kcUrl = (env.KC_URL || env.VITE_KC_URL || 'http://localhost:8085').replace(/\/+$/, '')
  const kcRealm = env.KC_REALM || env.VITE_KC_REALM || 'app-realm'

  return {
    plugins: [react(), tailwindcss(), runtimeConfigPlugin(env)],
    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url)),
      },
    },
    server: {
      // `PORT` wins, so a second instance can run beside one already on 5173.
      port: Number(process.env.PORT) || 5173,
      open: true,
      proxy: {
        /**
         * The API, forwarded unchanged — NO REWRITE: the backend serves
         * /app/v1/... at its root, so the browser's path IS the upstream path.
         *
         * `ws: true` because the MFA "approved" push is a WebSocket at
         * /app/v1/mfa/ws; without it the upgrade is dropped and the verdict
         * only arrives via the slower polling fallback.
         */
        '/app/v1': {
          target: apiUpstream,
          changeOrigin: true,
          ws: true,
          configure: (proxy) => {
            proxy.on('proxyReq', (proxyReq) => {
              /**
               * STRIP THE BROWSER'S `Origin`. A gateway running a strict CORS
               * policy may answer a disallowed origin with 200 AND AN EMPTY
               * BODY rather than a refusal — reads work, writes evaporate,
               * silently. Once the request is here it is server-to-server and
               * has no browser origin; `changeOrigin` does NOT do this — it
               * rewrites Host, not Origin.
               */
              proxyReq.removeHeader('origin')
            })
          },
        },
        /**
         * The Keycloak Admin REST API, for account provisioning. NOTHING IS
         * SUBSTITUTED: the signed-in administrator's own token is forwarded
         * (via the backend's /kcadmin in a container; directly here), so
         * Keycloak authorises against THEIR realm-management roles.
         */
        '/kcadmin': {
          target: kcUrl,
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/kcadmin/, `/admin/realms/${kcRealm}`),
        },
      },
    },
    build: {
      rollupOptions: {
        output: {
          /**
           * Vendor code pinned to its own chunk so it survives app deploys in
           * the browser cache — React and the router change on a dependency
           * bump, not on every release. Everything else splits by route
           * (React.lazy in routes/manifest.tsx).
           */
          manualChunks: {
            react: ['react', 'react-dom', 'react-router-dom'],
          },
        },
      },
    },
  }
})
